package Models;

public enum Token {
    IDENTIFIER,STRING,INTEGER,FLOAT,PLUS,MINUS,TIMES,DIVIDE,KEYWORD,INVALID,
    ASSIGNMENT_OPERATOR,SEMICOLON, AND,LEFT_PARENTHESIS, RIGHT_PARENTHESIS,COMMA,DOT,DOTDOT,COLON,EQUAL, LOWER_OR_EQUALS, GREATER_OR_EQUALS, NOT_EQUALS, GREATER_THAN, LOWER_THAN, AT_SIGN,
    LEFT_BRACE, RIGHT_BRACE, DECREMENTAL,INCREMENTAL, MAIN, OR
}
 
